## 1 . Load this data in pandas with a relation in sql

In [1]:
import mysql.connector
from mysql.connector import Error
from sqlalchemy import create_engine
import pandas as pd
pd.set_option('display.max_columns',24)

In [2]:
sup = pd.read_excel('/Users/barnalikkapradhan/Downloads/superstore.xlsx')
sup

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [3]:
ret = pd.read_excel('/Users/barnalikkapradhan/Downloads/superstore.xlsx',sheet_name = 'Returns')
ret

      Order ID    Status
0           65  Returned
1          612  Returned
2          614  Returned
3          678  Returned
4          710  Returned
...        ...       ...
1629    182681  Returned
1630    182683  Returned
1631    182750  Returned
1632    182781  Returned
1633    182906  Returned

[1634 rows x 2 columns]

In [4]:
sup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

## 2. Load the data in bulk in table

In [5]:
engine = create_engine('mysql+mysqlconnector://root:Boomclap4!@localhost:3306/TESTO',echo=False)

In [6]:
sup.to_sql('SUPERSTORE', con= engine, if_exists='append', index = False)

## 3 . Find out how return that we have received

In [9]:
d= ret['Status']
d.value_counts()

Returned    1634
Name: Status, dtype: int64

## 4 . Try  to join order and return data both in pandas

In [10]:
combo = pd.merge(sup,ret,on='Order ID',how='outer').drop_duplicates().reset_index(drop=True)
combo

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,...,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status
0,18606.0,Not Specified,0.01,2.88,0.50,2.0,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,...,0.36,Central,Illinois,Addison,60101.0,2012-05-28,2012-05-30,1.3200,2.0,5.90,88525,NaN
1,20847.0,High,0.01,2.84,0.93,3.0,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,...,0.54,West,Washington,Anacortes,98221.0,2010-07-07,2010-07-08,4.5600,4.0,13.01,88522,NaN
2,23086.0,Not Specified,0.03,6.68,6.15,3.0,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,...,0.37,West,Washington,Anacortes,98221.0,2011-07-27,2011-07-28,-47.6400,7.0,49.92,88523,NaN
3,23087.0,Not Specified,0.01,5.68,3.60,3.0,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,...,0.56,West,Washington,Anacortes,98221.0,2011-07-27,2011-07-28,-30.5100,7.0,41.64,88523,NaN
4,23088.0,Not Specified,0.00,205.99,2.50,3.0,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,...,0.59,West,Washington,Anacortes,98221.0,2011-07-27,2011-07-27,998.2023,8.0,1446.67,88523,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182681,Returned
10995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182683,Returned
10996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182750,Returned
10997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182781,Returned
10998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182906,Returned

## 5. Try to find out how many unique customer that we have

In [11]:
n = len(pd.unique(combo['Customer ID']))
print("No of unique Customer Id's :",n)

No of unique Customer Id's : 2704

## 6. Try to find out in how many regions we are selling a product and who is a manager for a respective region

In [12]:
det = pd.read_excel('/Users/barnalikkapradhan/Downloads/superstore.xlsx',sheet_name = 'Users')
det

    Region  Manager
0  Central    Chris
1     East     Erin
2    South      Sam
3     West  William

## 7. Find out how many different shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset

In [13]:
d=combo['Ship Mode']
d.value_counts()

Regular Air       7036
Delivery Truck    1283
Express Air       1107
Name: Ship Mode, dtype: int64

In [14]:
combo['Ship Mode'].value_counts(normalize=True)*100

Regular Air       74.644600
Delivery Truck    13.611288
Express Air       11.744112
Name: Ship Mode, dtype: float64

## 8 . Create a new coulmn and try to find our a diffrence between order date and shipment date

In [15]:
combo['Diff_of_days'] = (combo['Ship Date'] - combo['Order Date']).dt.days
combo

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status,Diff_of_days
0,18606.0,Not Specified,0.01,2.88,0.50,2.0,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,...,Central,Illinois,Addison,60101.0,2012-05-28,2012-05-30,1.3200,2.0,5.90,88525,NaN,2.0
1,20847.0,High,0.01,2.84,0.93,3.0,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,...,West,Washington,Anacortes,98221.0,2010-07-07,2010-07-08,4.5600,4.0,13.01,88522,NaN,1.0
2,23086.0,Not Specified,0.03,6.68,6.15,3.0,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,...,West,Washington,Anacortes,98221.0,2011-07-27,2011-07-28,-47.6400,7.0,49.92,88523,NaN,1.0
3,23087.0,Not Specified,0.01,5.68,3.60,3.0,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,...,West,Washington,Anacortes,98221.0,2011-07-27,2011-07-28,-30.5100,7.0,41.64,88523,NaN,1.0
4,23088.0,Not Specified,0.00,205.99,2.50,3.0,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,...,West,Washington,Anacortes,98221.0,2011-07-27,2011-07-27,998.2023,8.0,1446.67,88523,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182681,Returned,NaN
10995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182683,Returned,NaN
10996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182750,Returned,NaN
10997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182781,Returned,NaN
10998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182906,Returned,NaN

## 9 . Based on question number 8 find out for which order id we have shipment duration more than 10 days

In [16]:
H= combo[combo['Diff_of_days'] >10]
H

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status,Diff_of_days
643,18246.0,Critical,0.05,11.09,5.25,250.0,Brenda Nelson Blanchard,Regular Air,Corporate,Office Supplies,Envelopes,Small Box,...,Central,Minnesota,Richfield,55423.0,2011-12-29,2012-03-22,58.5000,19.0,204.67,87215,NaN,84.0
1548,23091.0,Medium,0.04,100.98,7.18,595.0,Dana Desai,Regular Air,Small Business,Technology,Computer Peripherals,Small Box,...,Central,Indiana,Bloomington,47401.0,2011-12-30,2012-01-10,375.7050,6.0,587.46,86318,NaN,11.0
1549,23092.0,Medium,0.09,6.48,7.49,595.0,Dana Desai,Express Air,Small Business,Office Supplies,Paper,Small Box,...,Central,Indiana,Bloomington,47401.0,2011-12-30,2012-01-14,-47.3950,12.0,79.37,86318,NaN,15.0
1678,20703.0,Not Specified,0.07,130.98,30.00,637.0,Christopher Bryant,Delivery Truck,Consumer,Furniture,Chairs & Chairmats,Jumbo Drum,...,West,California,Santa Clara,95051.0,2011-12-30,2012-01-16,-211.8850,21.0,2699.94,87957,NaN,17.0
1679,20704.0,Not Specified,0.09,55.98,4.86,637.0,Christopher Bryant,Regular Air,Consumer,Office Supplies,Paper,Small Box,...,West,California,Santa Clara,95051.0,2011-12-30,2012-01-10,355.0119,10.0,514.51,87957,NaN,11.0
1680,20705.0,Not Specified,0.08,115.99,4.23,637.0,Christopher Bryant,Regular Air,Consumer,Technology,Telephones and Communication,Small Box,...,West,California,Santa Clara,95051.0,2011-12-30,2012-01-27,1021.4001,16.0,1480.29,87957,NaN,28.0
1697,2703.0,Not Specified,0.07,130.98,30.00,640.0,Neal Wolfe,Delivery Truck,Consumer,Furniture,Chairs & Chairmats,Jumbo Drum,...,West,Washington,Seattle,98119.0,2011-12-30,2012-01-16,-423.7700,83.0,10671.20,19556,NaN,17.0
1698,2704.0,Not Specified,0.09,55.98,4.86,640.0,Neal Wolfe,Regular Air,Consumer,Office Supplies,Paper,Small Box,...,West,Washington,Seattle,98119.0,2011-12-30,2012-01-10,469.6900,41.0,2109.51,19556,NaN,11.0
1699,2705.0,Not Specified,0.08,115.99,4.23,640.0,Neal Wolfe,Regular Air,Consumer,Technology,Telephones and Communication,Small Box,...,West,Washington,Seattle,98119.0,2011-12-30,2012-01-27,727.3620,65.0,6013.69,19556,NaN,28.0
2515,18060.0,Low,0.02,2.21,1.00,964.0,Virginia Rivera,Regular Air,Home Office,Office Supplies,Pens & Art Supplies,Wrap Bag,...,West,California,Redwood City,94061.0,2011-12-30,2012-03-31,5.8200,10.0,22.35,86177,NaN,92.0
5550,21603.0,Not Specified,0.02,5.58,1.99,2048.0,Ricky Dougherty,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,...,Central,South Dakota,Brookings,57006.0,2011-12-30,2012-01-13,66.2250,21.0,121.51,88223,NaN,14.0
5674,19005.0,Low,0.06,65.99,2.50,2088.0,Carrie Boyle,Regular Air,Corporate,Technology,Telephones and Communication,Small Box,...,East,New York,Mount Vernon,10550.0,2011-12-28,2012-01-14,187.4880,8.0,451.34,88352,NaN,17.0
5859,24392.0,Low,0.05,29.89,1.99,2143.0,Lester Sawyer,Regular Air,Home Office,Technology,Computer Peripherals,Small Pack,...,South,Virginia,Fairfax,20151.0,2011-12-26,2012-01-17,4230.2001,12.0,344.16,87572,NaN,22.0
5881,21257.0,Low,0.05,7.99,5.03,2153.0,Anna Glenn,Regular Air,Home Office,Technology,Telephones and Communication,Medium Box,...,West,California,Pasadena,91104.0,2011-12-26,2012-01-19,-23.4520,2.0,15.56,91294,NaN,24.0
8607,26351.0,Medium,0.00,8.32,2.38,3119.0,Jay Hubbard,Express Air,Corporate,Technology,Computer Peripherals,Small Pack,...,South,Florida,Orlando,32839.0,2011-12-29,2012-01-16,-1075.3960,19.0,170.62,86434,NaN,18.0
8609,26350.0,Medium,0.07,180.98,55.24,3119.0,Jay Hubbard,Delivery Truck,Corporate,Office Supplies,Appliances,Jumbo Drum,...,South,Florida,Orlando,32839.0,2013-12-29,2014-01-15,-147.5180,25.0,4529.95,86436,NaN,17.0
8610,26352.0,Medium,0.06,4.20,2.26,3119.0,Jay Hubbard,Regular Air,Corporate,Office Supplies,Paper,Wrap Bag,...,South,Florida,Orlando,32839.0,2013-12-29,2014-01-17,-689.8738,2.0,9.64,86436,NaN,19.0
8973,20750.0,Low,0.06,125.99,8.08,3248.0,Earl Donnelly,Express Air,Corporate,Technology,Telephones and Communication,Small Box,...,South,Louisiana,Slidell,70458.0,2011-12-26,2012-01-14,2.4780,20.0,2180.31,87300,NaN,19.0
8974,20748.0,Low,0.03,11.97,5.81,3252.0,Milton Harrell,Regular Air,Corporate,Office Supplies,Pens & Art Supplies,Small Pack,...,East,New York,Rotterdam,12306.0,2011-12-26,2012-01-22,-15.8700,8.0,100.26,87300,NaN,27.0
8975,20749.0,Low,0.08,195.99,4.20,3252.0,Milton Harrell,Regular Air,Corporate,Technology,Telephones and Communication,Small Box,...,East,New York,Rotterdam,12306.0,2011-12-26,2012-01-26,-278.9765,3.0,482.78,87300,NaN,31.0
8984,2748.0,Low,0.03,11.97,5.81,3251.0,Peter Brooks,Regular Air,Corporate,Office Supplies,Pens & Art Supplies,Small Pack,...,East,New York,New York City,10112.0,2011-12-26,2012-01-22,-31.7400,31.0,388.52,19841,NaN,27.0
8985,2749.0,Low,0.08,195.99,4.20,3251.0,Peter Brooks,Regular Air,Corporate,Technology,Telephones and Communication,Small Box,...,East,New York,New York City,10112.0,2011-12-26,2012-01-26,-557.9530,13.0,2092.05,19841,NaN,31.0
8986,2750.0,Low,0.06,125.99,8.08,3251.0,Peter Brooks,Express Air,Corporate,Technology,Telephones and Communication,Small Box,...,East,New York,New York City,10112.0,2013-12-26,2014-01-14,1304.5590,86.0,9375.35,19841,NaN,19.0

## 10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well

In [17]:
# This gives us the list of returned orders.
r =combo[combo['Status'] == 'Returned']
r

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status,Diff_of_days
49,1359.0,Low,0.05,5.85,2.27,21.0,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,...,East,New York,New York City,10012.0,2011-04-20,2011-04-24,-6.8200,9.0,54.79,9895,Returned,4.0
317,1950.0,Medium,0.01,4.91,0.50,117.0,Linda Weiss,Regular Air,Home Office,Office Supplies,Labels,Small Box,...,West,Washington,Seattle,98103.0,2010-04-04,2010-04-06,112.0600,47.0,228.46,13959,Returned,2.0
318,1951.0,Medium,0.09,4.00,1.30,117.0,Linda Weiss,Express Air,Home Office,Office Supplies,Paper,Wrap Bag,...,West,Washington,Seattle,98103.0,2010-04-04,2010-04-06,16.7900,19.0,77.61,13959,Returned,2.0
324,5055.0,High,0.02,3.28,5.00,117.0,Linda Weiss,Regular Air,Home Office,Office Supplies,Pens & Art Supplies,Wrap Bag,...,West,Washington,Seattle,98103.0,2013-08-16,2013-08-18,-89.0600,52.0,190.52,36038,Returned,2.0
734,5573.0,Low,0.02,11.97,5.81,272.0,Eleanor Swain,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Small Pack,...,South,North Carolina,Charlotte,28204.0,2013-08-12,2013-08-12,-81.9413,76.0,912.06,39490,Returned,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182681,Returned,NaN
10995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182683,Returned,NaN
10996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182750,Returned,NaN
10997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182781,Returned,NaN
10998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,182906,Returned,NaN

In [18]:
#From that list of returned orders we find that none of them have shiiping orders exceeding 15 days.
shipment_duration = r[r['Diff_of_days'] > 15]
shipment_duration

Empty DataFrame
Columns: [Row ID, Order Priority, Discount, Unit Price, Shipping Cost, Customer ID, Customer Name, Ship Mode, Customer Segment, Product Category, Product Sub-Category, Product Container, Product Name, Product Base Margin, Region, State or Province, City, Postal Code, Order Date, Ship Date, Profit, Quantity ordered new, Sales, Order ID, Status, Diff_of_days]
Index: []

[0 rows x 26 columns]

## 11 . Group by region and find out which region is more profitable

In [19]:
group = combo.groupby(["Region"]).sum()
Profit_acc_to_Region = group["Profit"]
Profit_acc_to_Region.nlargest(1)

Region
Central    519825.567067
Name: Profit, dtype: float64

## 12 . Try to find out overalll in which country we are giving more didscount

In [20]:
#California gives the highest number of discounts on products.
d=combo['State or Province']
d.value_counts()

California              1021
Texas                    646
Illinois                 584
New York                 574
Florida                  522
Ohio                     396
Washington               327
Michigan                 327
Pennsylvania             271
North Carolina           251
Indiana                  241
Minnesota                239
Massachusetts            222
Georgia                  214
Virginia                 198
Maryland                 178
Colorado                 177
New Jersey               177
Wisconsin                169
Oregon                   168
Tennessee                166
Missouri                 161
Iowa                     156
Utah                     146
Arizona                  134
Kansas                   133
Maine                    128
Alabama                  125
Arkansas                 123
Idaho                    114
South Carolina           105
Oklahoma                 104
Louisiana                 89
New Mexico                84
Kentucky                  83
Connecticut               82
Mississippi               78
Nebraska                  77
District of Columbia      68
Vermont                   61
New Hampshire             54
Montana                   49
West Virginia             43
Nevada                    43
North Dakota              34
South Dakota              28
Wyoming                   21
Rhode Island              20
Delaware                  15
Name: State or Province, dtype: int64

## 13 . Give me a list of unique postal code

In [21]:
n = len(pd.unique(combo['Postal Code']))
print("No of unique Postal Code :",n)

No of unique Postal Code : 1698

## 14 . Which customer segement is more profitalble find it out .

In [22]:
group = combo.groupby(["Customer Segment"]).sum()
Profit_acc_to_CustomerSeg = group["Profit"]
Profit_acc_to_CustomerSeg.nlargest(1)

Customer Segment
Corporate    505538.627783
Name: Profit, dtype: float64

## 15 . Try to find out the 10th most loss making product catagory

In [23]:
tenth_loss = combo.nsmallest(n=10,columns=['Profit'])
tenth_loss

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status,Diff_of_days
4659,18306.0,Medium,0.08,175.99,4.99,1738.0,Dean Solomon,Regular Air,Corporate,Technology,Telephones and Communication,Small Box,...,South,North Carolina,Gastonia,28052.0,2010-03-28,2010-03-28,-16476.838000,10.0,1486.34,85865,NaN,0.0
4338,20972.0,Low,0.01,24.95,2.99,1632.0,Lori Wolfe,Regular Air,Home Office,Office Supplies,Binders and Binder Accessories,Small Box,...,South,Mississippi,Hattiesburg,39401.0,2012-05-21,2012-05-21,-14369.123580,3.0,81.31,90534,NaN,0.0
7803,23213.0,Low,0.09,6783.02,24.49,2855.0,Vicki Womble,Regular Air,Consumer,Technology,Office Machines,Large Box,...,West,Washington,Des Moines,98198.0,2010-03-10,2010-03-14,-14140.701600,1.0,6296.00,87317,NaN,4.0
4844,21284.0,Critical,0.04,880.98,44.55,1793.0,Derek Jernigan,Delivery Truck,Home Office,Furniture,Bookcases,Jumbo Box,...,Central,Illinois,Galesburg,61401.0,2010-01-06,2010-01-07,-13706.464000,8.0,6968.90,87853,NaN,1.0
5402,24076.0,Medium,0.04,6783.02,24.49,2004.0,James Dickinson Ball,Regular Air,Home Office,Technology,Office Machines,Large Box,...,West,Montana,Bozeman,59715.0,2010-10-17,2010-10-19,-13562.637408,1.0,6569.07,91277,NaN,2.0
5409,22942.0,High,0.05,3502.14,8.73,2006.0,Cynthia Khan,Delivery Truck,Home Office,Technology,Office Machines,Jumbo Box,...,West,Colorado,Durango,81301.0,2011-01-18,2011-01-19,-10402.943916,1.0,3460.11,88799,NaN,1.0
7725,21048.0,Not Specified,0.06,6783.02,24.49,2825.0,Carole Rosen,Regular Air,Consumer,Technology,Office Machines,Large Box,...,West,Idaho,Boise,83701.0,2011-09-12,2011-09-14,-10263.659700,2.0,9507.12,89498,NaN,2.0
2191,21575.0,Not Specified,0.05,3499.99,24.49,838.0,Gary Walton,Regular Air,Consumer,Technology,Copiers and Fax,Large Box,...,West,California,Hacienda Heights,91745.0,2013-10-02,2013-10-03,-9078.940000,2.0,6849.48,89896,NaN,1.0
4068,21917.0,High,0.06,3502.14,8.73,1530.0,Seth Sweeney,Delivery Truck,Consumer,Technology,Office Machines,Jumbo Box,...,West,California,Palm Springs,92262.0,2012-07-07,2012-07-09,-8570.448300,1.0,3057.44,88853,NaN,2.0
4857,24251.0,High,0.05,3502.14,8.73,1796.0,Carlos Johnson,Delivery Truck,Corporate,Technology,Office Machines,Jumbo Box,...,West,California,San Francisco,94110.0,2013-03-23,2013-03-24,-7961.430900,1.0,3360.30,90778,NaN,1.0

In [24]:
# Technology is the tenth most lost making Product Category. 
tenth_loss.iloc[9:10]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status,Diff_of_days
4857,24251.0,High,0.05,3502.14,8.73,1796.0,Carlos Johnson,Delivery Truck,Corporate,Technology,Office Machines,Jumbo Box,...,West,California,San Francisco,94110.0,2013-03-23,2013-03-24,-7961.4309,1.0,3360.3,90778,NaN,1.0

## 16 . Try to find out 10 top  product with highest margins

In [25]:
group = combo.groupby(["Product Name"]).sum()
Product = group["Product Base Margin"]
Product.nlargest(10)

Product Name
Global High-Back Leather Tilter, Burgundy                                                    19.98
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables                            18.33
Bevis 36 x 72 Conference Tables                                                              16.38
Adesso Programmable 142-Key Keyboard                                                         15.45
Accessory36                                                                                  14.11
Office Star - Mid Back Dual function Ergonomic High Back Chair with 2-Way Adjustable Arms    13.64
Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum                13.26
Microsoft Internet Keyboard                                                                  13.21
StarTAC 7760                                                                                 12.98
Bell Sonecor JB700 Caller ID                                                                 12.60
Name: Product Base Margin, dtype: float64